<?php
/*
# CONFIGURACIÓN DE BASE DE DATOS PRINCIPAL
DB_HOST=127.0.0.1
DB_PORT=3306
DB_NAME=api_system
DB_USER=root
DB_PASSWORD=secret
DB_CHARSET=utf8mb4

# CONFIGURACIÓN DE BASE DE DATOS EXTERNA
DB_EXT_HOST=127.0.0.1
DB_EXT_PORT=3306
DB_EXT_NAME=bro
DB_EXT_USER=root
DB_EXT_PASSWORD=secret
DB_EXT_CHARSET=utf8mb4

# CONFIGURACIÓN DE API
API_TOKEN=your_api_token_here
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin123

# CONFIGURACIÓN DE ENTORNO
APP_ENV=development
TIMEZONE=America/Mexico_City

# CONFIGURACIÓN DE SEGURIDAD
MAX_QUERY_EXECUTION_TIME=30
MAX_CONNECTIONS=10
RATE_LIMIT_PER_MINUTE=100

*/    
